import os
import re
import pandas as pd

# ================= 配置区域 =================

INPUT_FOLDER = "英文中方"
OUTPUT_FOLDER = "Cleaned_Chinese_Trans_V3"
REPORT_FILE = "deleted_report_cn_v3.csv"

# 已知的翻译组/编辑组名称（全部小写，用于精确匹配独立成行的情况）
KNOWN_TRANSLATOR_NAMES = {
    "dragon boat translation",
    "translation nation",
}

# ================= 局部清洗 =================

def remove_url_only(line):
    """
    只删除行内的 URL 链接，保留其他文字，并规范化多余空格。
    """
    url_pattern = r'https?://\S+|www\.[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+\S*'
    clean_line = re.sub(url_pattern, '', line)
    # 规范化：多个空格合并为一个，去掉首尾空格
    clean_line = re.sub(r' {2,}', ' ', clean_line).strip()
    return clean_line


# ================= 整行删除逻辑 =================

def get_junk_reason_cn_v3(line, line_idx=0, total_lines=0):
    line = line.strip()
    if not line:
        return "Empty Line"

    lower_line = line.lower()

    # ===== 对话保护：以引号开头的行通常是正文对话，不删 =====
    if line.startswith('"') or line.startswith('\u201c') or line.startswith("'"):
        # 但如果整行恰好是已知翻译组名（极端情况），仍然删
        stripped = lower_line.strip('"\u201c\u201d\'')
        if stripped not in KNOWN_TRANSLATOR_NAMES:
            return None

    # =============================================================
    #  精确匹配：用户人工确认的 5 类垃圾模式
    # =============================================================

    # --- 问题1: "Generated by NovelGet.com" ---
    #     仅当 "Generated by" 后面紧跟域名时才删除，避免误删正文
    if re.search(r'generated\s+by\s+[a-zA-Z0-9-]+\.(com|net|org|io|co|me|info|xyz)\b', lower_line):
        return "网站生成水印(Generated by)"

    # 通用域名检测（捕获 NovelGet.com, boxnovel.com 等残留域名）
    if re.search(r'\b[a-zA-Z0-9-]+\.(com|net|org|io|co|me|info|xyz)\b', lower_line):
        return "包含域名"

    # --- 问题2: "Please go to to read the latest chapters for free" ---
    #     URL 被剥离后残留 "to to"，用宽松匹配
    if "please go to" in lower_line and ("read" in lower_line or "chapter" in lower_line or "free" in lower_line):
        return "阅读推广链接"

    # --- 问题3: "Previous Chapter Next Chapter" 章节导航 ---
    if "previous chapter" in lower_line or "next chapter" in lower_line:
        return "章节导航"
    if "table of contents" in lower_line:
        return "目录导航"

    # --- 问题4 & 5: Translator / Editor 块（单行 & 多行） ---

    #  (a) 单行开头匹配: "Translator:" "Editor:" "TL:" "T/N:" 等
    if re.match(r'^(Translator|Editor|TL|Trans|T/N|Epub|Credits?)\s?[:：]', line, re.IGNORECASE):
        return "翻译人员名单"

    #  (b) 行内包含 "Translator:" 或 "Editor:" + 名字
    if re.search(r'\b(Translator|Editor|Epub|Credit):\s*[A-Za-z]', line):
        return "翻译人员名单"

    #  (c) 组合行: "Translator: XXX Editor: XXX" 写在同一行
    if re.search(r'translator\s*[:：]\s*.+?\s+editor\s*[:：]', lower_line):
        return "翻译/编辑合并行"

    #  (d) 已知翻译组名称独立成行（精确匹配）
    if lower_line in KNOWN_TRANSLATOR_NAMES:
        return "翻译组名称"

    # =============================================================
    #  其他通用垃圾模式（保留原有规则）
    # =============================================================

    # 求打赏 / 求票
    if "patreon" in lower_line or "ko-fi" in lower_line or "paypal" in lower_line:
        return "求打赏(Patreon/Paypal)"
    if "vote for" in lower_line and ("stone" in lower_line or "chapter" in lower_line):
        return "求票/求推荐"

    # 网站防盗版水印
    if "read on" in lower_line and ("webnovel" in lower_line or "wuxia" in lower_line or "site" in lower_line):
        return "防盗版水印"
    if "boxnovel" in lower_line:
        return "BoxNovel广告"
    if "you're reading" in lower_line and "novel" in lower_line:
        return "阅读提示广告"

    # 下章预告
    if lower_line == "teaser" or lower_line == "preview":
        return "下章预告标题"

    # NovelFull 水印
    if "you're reading on novelfull thanks!" in lower_line:
        return "NovelFull水印"

    # 版权声明
    if "copyright" in lower_line and "rights reserved" in lower_line:
        return "版权声明"

    # 故事描述 / 原文链接
    if re.match(r'^Story Description:', line, re.IGNORECASE):
        return "故事描述"
    if re.match(r'^Original Story can be found here:', line, re.IGNORECASE):
        return "原文链接"

    # 章节推广
    if re.search(r'chapter.*release.*push.*back|promote.*new.*book|unlock.*chapter.*coin', lower_line):
        return "章节推广信息"
    if re.search(r'this chapter.*release|final chapter.*release.*tomorrow', lower_line):
        return "章节发布信息"

    # 纯分割线（非字母数字字符组成的行）
    clean_chars = re.sub(r'\s+', '', line)
    if len(clean_chars) > 3 and not any(c.isalnum() for c in clean_chars):
        return "纯分割线"

    # 结尾区域特殊处理（最后 20 行）
    if total_lines > 0 and line_idx >= total_lines - 20:
        if re.search(r'^(translator|editor|epub|credit|thoughts?):', lower_line):
            return "结尾致谢/名单"
        if re.search(r'continue.*support|thank.*support|next.*project|been.*long.*ride', lower_line):
            return "结尾推广信息"

    return None


# ================= 主程序 =================

def main():
    if not os.path.exists(INPUT_FOLDER):
        print(f"错误：找不到文件夹 '{INPUT_FOLDER}'")
        return

    if not os.path.exists(OUTPUT_FOLDER):
        os.makedirs(OUTPUT_FOLDER)

    files = [f for f in os.listdir(INPUT_FOLDER) if f.endswith('.txt')]

    print(f"找到 {len(files)} 个 txt 文件，开始清洗 ...")
    audit_records = []

    for file_name in files:
        file_path = os.path.join(INPUT_FOLDER, file_name)
        output_path = os.path.join(OUTPUT_FOLDER, "clean_" + file_name)
        clean_lines = []

        # --- 文件读取 ---
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                raw_lines = f.readlines()
        except:
            with open(file_path, 'r', encoding='latin-1') as f:
                raw_lines = f.readlines()

        total_lines = len(raw_lines)

        for idx, line in enumerate(raw_lines):
            original_line = line.strip()

            # Step 1: 检测并剥离 URL
            url_pattern = r'https?://\S+|www\.[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+\S*'
            has_url = bool(re.search(url_pattern, original_line))

            content_after_url_removal = remove_url_only(original_line)

            # Step 2: 对剥离 URL 后的内容进行垃圾检测
            reason = get_junk_reason_cn_v3(
                content_after_url_removal, idx, total_lines
            )

            # Step 3: 记录与输出
            if has_url:
                audit_records.append({
                    "文件名": file_name,
                    "行号": idx + 1,
                    "原内容": original_line[:50],
                    "原因": "URL删除"
                })

            if reason is None:
                # 保留有效内容
                if content_after_url_removal:
                    clean_lines.append(content_after_url_removal)
            elif reason == "Empty Line":
                continue
            else:
                audit_records.append({
                    "文件名": file_name,
                    "行号": idx + 1,
                    "原内容": original_line[:50],
                    "原因": reason
                })

        with open(output_path, 'w', encoding='utf-8') as f_out:
            f_out.write("\n\n".join(clean_lines))

    # ---- 输出报告 ----

    if audit_records:
        df = pd.DataFrame(audit_records)
        df.to_csv(REPORT_FILE, index=False, encoding='utf-8-sig')
        print(f"审计报告已生成: {REPORT_FILE}")
        print(f"清洗版文件保存在: {OUTPUT_FOLDER}/")
        print(f"此次共处理了 {len(df)} 条记录。")

        # 按原因分类统计
        reason_counts = df["原因"].value_counts()
        print("\n--- 删除原因统计 ---")
        for reason, count in reason_counts.items():
            print(f"  {reason}: {count} 条")
    else:
        print("没有发现需要删除的垃圾。")


if __name__ == "__main__":
    main()
